# Generated by Django 4.2.3 on 2023-07-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file_date', models.TextField()),
                ('import_date', models.TextField()),
                ('record_count', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.TextField(unique=True)),
                ('planNumber', models.TextField()),
                ('versionNumber', models.TextField()),
                ('filename', models.TextField()),
                ('archive_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('awaiting_auction', 'Awaiting Auction'), ('auction_won', 'Auction Won'), ('auction_lost', 'Auction Lost')], default='new', max_length=20)),
                ('auction_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completion_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.TextField()),
                ('total_price', models.FloatField()),
                ('purchase_object_info', models.TextField()),
                ('publish_year', models.IntegerField()),
                ('purchase_files', models.IntegerField()),
                ('externalId_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_app.purchaseplanmodel', to_field='externalId')),
                ('purchase_files_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_app.purchasefilesmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='purchasemodel',
            constraint=models.UniqueConstraint(fields=('externalId',), name='unique_externalId'),
        ),
    ]
