# Generated by Django 4.2.3 on 2023-07-07 11:53

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0004_alter_requestmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='auction_date',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='bid_security_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер обеспечения заявки'),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='bid_submission_deadline',
            field=models.DateTimeField(default=timezone.now().strftime('%Y-%m-%dT%H:%M:%S'), verbose_name='Дата и время окончания срока подачи заявок (dd.mm.YYYY mm:hh) timedate (UTC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='contract_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения контракта'),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='initial_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Начальная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='purchase_name',
            field=models.TextField(default='default', verbose_name='Наименование закупки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='registry_number',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Реестровый номер извещения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='warranty_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок гарантии'),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='warranty_security_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер обеспечения гарантии'),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='work_security_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер обеспечения работ'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('manually_filtered', 'Отфильтрована (вручную)'), ('auto_filtered', 'Отфильтрована (автоматически)'), ('in_progress', 'В работе'), ('not_participating_objectively', 'Не участвуем (объективно)'), ('not_participating_subjectively', 'Не участвуем (субъективно)'), ('bid_submission', 'Подача заявки'), ('bid_submitted', 'Заявка подана'), ('auction', 'Торги'), ('auction_completed_return_security', 'Торги завершены (возврат обеспечения)'), ('auction_completed', 'Торги завершены'), ('contract_signing', 'Подписание контракта'), ('contract_signed', 'Контракт подписан'), ('contract_executed', 'Контракт исполнен')], default='new', max_length=150, verbose_name='Статус'),
        ),
    ]
