# Generated by Django 4.2.3 on 2023-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0006_alter_requestmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='contract_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения контракта'),
        ),
    ]
