# Generated by Django 4.2.3 on 2023-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0007_alter_requestmodel_contract_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='registry_number',
            field=models.CharField(max_length=75, verbose_name='Реестровый номер извещения'),
        ),
    ]
