# Generated by Django 4.2.3 on 2023-07-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0011_staterequestmodel_alter_requestmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.staterequestmodel'),
        ),
    ]
